Extract xcodebuild-has-exited check

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -22,6 +22,19 @@ jobs:
         with:
           working-directory: fixtures/debug
 
+  xcodebuild-has-exited:
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: ./
+        with:
+          working-directory: fixtures/debug
+      - run: |
+          if pgrep -a xcodebuild; then
+            echo >&2 "error: xcodebuild is still running"
+            exit 1
+          fi
+
   executable-runs:
     runs-on: macos-latest
     steps:
@@ -31,14 +44,10 @@ jobs:
           action: build
           working-directory: fixtures/executable
       - run: |
-          if pgrep -a xcodebuild; then
-            echo >&2 "error: xcodebuild is still running"
-            exit 1
-          fi
           OUT=$(~/Library/Developer/Xcode/DerivedData/executable-*/Build/Products/Debug/my-fixture)
           if [[ "${OUT}" != 'Hello, world!' ]]; then
             echo >&2 "error: output of my-fixture was unexpected: ${OUT}"
-            exit 2
+            exit 1
           fi
 
   invalid-action-fails:
